CREATE DATABASE `uranus`;

CREATE TABLE `uranus`.`company` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(62) NOT NULL,
  `EMAIL` varchar(50) NOT NULL,
  `PHONE` int(14) DEFAULT NULL,
  `MANAGER` varchar(62) DEFAULT NULL,
  `STATUS` int(1) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID_UNIQUE` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3;

CREATE TABLE `uranus`.`rule` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `ID_COMPANY` int(10) NOT NULL,
  `STRING` varchar(60) NOT NULL,
  `SOURCE` varchar(32) NOT NULL,
  `FILTER` longtext NOT NULL,
  `SCORE` varchar(10) NOT NULL,
  `DESCRIPTION` varchar(64) NOT NULL,
  `STATUS` int(1) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID_UNIQUE` (`ID`),
  KEY `ID_COMPANY_idx` (`ID_COMPANY`),
  CONSTRAINT `FK_ID_COMPANY_I` FOREIGN KEY (`ID_COMPANY`) REFERENCES `company` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=3;

CREATE TABLE `uranus`.`alert` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `ID_COMPANY` int(10) NOT NULL,
  `CONTENT` longtext NOT NULL,
  `DATETIME` datetime NOT NULL DEFAULT current_timestamp(),
  `STATUS` int(1) NOT NULL,
  `NOTIFICATION` int(1) NOT NULL,
  `HASH` char(32) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID_UNIQUE` (`ID`),
  UNIQUE KEY `HASH_UNIQUE` (`HASH`),
  KEY `ID_COMPANY_idx` (`ID_COMPANY`),
  CONSTRAINT `FK_ID_COMPANY_II` FOREIGN KEY (`ID_COMPANY`) REFERENCES `company` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=3;

CREATE TABLE `uranus`.`history` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `ID_COMPANY` int(10) NOT NULL,
  `DATETIME` datetime NOT NULL DEFAULT current_timestamp(),
  `ENGINE` varchar(32) NOT NULL,
  `RULE_QTT` int(10) NOT NULL,
  `EVENT_QTT` int(10) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID_UNIQUE` (`ID`),
  KEY `ID_COMPANY_idx` (`ID_COMPANY`),
  CONSTRAINT `FK_ID_COMPANY_III` FOREIGN KEY (`ID_COMPANY`) REFERENCES `company` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=3;