name: Audit code for security bugs and best-pratictes
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Audit code
      run: |
        git clone https://github.com/htrgouvea/secureperl && cd secureperl
        docker build -t secureperl .
        docker run -ti --rm secureperl 